/**
 * Native OS Diagnostics & Hardware Telemetry (Node kernel APIs & OS CLI bridge).
 * Provides deterministic, offline-capable hardware queries, process inspection,
 * desktop folder auditing, and screen recording discovery.
 * Never generated by an LLM. Never hallucinated.
 */

const os = require('os');
const path = require('path');
const fs = require('fs');
const { execFile, spawn } = require('child_process');

function gb(bytes) {
  const n = Number(bytes);
  if (!Number.isFinite(n) || n < 0) return 0;
  return Math.round((n / (1024 ** 3)) * 10) / 10;
}

function mb(bytes) {
  const n = Number(bytes);
  if (!Number.isFinite(n) || n < 0) return 0;
  return Math.round((n / (1024 ** 2)) * 10) / 10;
}

function cpuTimes() {
  let idle = 0;
  let total = 0;
  const list = os.cpus() || [];
  for (const cpu of list) {
    const t = cpu.times || {};
    idle += Number(t.idle) || 0;
    total += (Number(t.user) || 0) + (Number(t.nice) || 0) + (Number(t.sys) || 0) + (Number(t.idle) || 0) + (Number(t.irq) || 0);
  }
  return { idle, total };
}

function ramSnapshot() {
  const total = os.totalmem();
  const free = os.freemem();
  const used = Math.max(0, total - free);
  return {
    totalBytes: total,
    freeBytes: free,
    usedBytes: used,
    totalGb: gb(total),
    usedGb: gb(used),
    freeGb: gb(free),
    percent: total ? Math.round((used / total) * 1000) / 10 : 0
  };
}

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

async function cpuSnapshot() {
  const a = cpuTimes();
  await sleep(150);
  const b = cpuTimes();
  const idle = b.idle - a.idle;
  const total = b.total - a.total;
  const percent = total > 0 ? Math.round((1 - idle / total) * 1000) / 10 : 0;
  const cpus = os.cpus() || [];
  return {
    percent: Math.min(100, Math.max(0, percent)),
    cores: cpus.length,
    model: (cpus[0] && cpus[0].model) || 'CPU'
  };
}

/**
 * Battery telemetry across Windows, macOS, and Linux.
 */
function batterySnapshot() {
  if (process.platform === 'win32') {
    return new Promise((resolve) => {
      execFile(
        'powershell.exe',
        [
          '-NoProfile',
          '-NonInteractive',
          '-Command',
          `try {
            $b = Get-CimInstance -ClassName Win32_Battery -ErrorAction Stop | Select-Object -First 1;
            if (-not $b) { "{}" } else {
              $status = [int]$b.BatteryStatus;
              $statusText = switch ($status) {
                1 { "Discharging (On Battery)" }
                2 { "AC Connected" }
                3 { "Fully Charged" }
                4 { "Low" }
                5 { "Critical" }
                6 { "Charging" }
                7 { "Charging and High" }
                8 { "Charging and Low" }
                9 { "Charging and Critical" }
                default { "On Battery" }
              };
              $isCharging = ($status -in 2, 6, 7, 8, 9);
              @{ percent = [int]$b.EstimatedChargeRemaining; status = $status; statusText = $statusText; charging = $isCharging } | ConvertTo-Json -Compress
            }
          } catch { "{}" }`
        ],
        { timeout: 5000, windowsHide: true, maxBuffer: 65536 },
        (err, stdout) => {
          if (err) {
            resolve(null);
            return;
          }
          try {
            const j = JSON.parse(String(stdout || '{}').trim() || '{}');
            if (j.percent == null || !Number.isFinite(Number(j.percent))) resolve(null);
            else {
              resolve({
                percent: Number(j.percent),
                charging: !!j.charging,
                status: j.status,
                statusText: j.statusText || (j.charging ? 'Charging' : 'On Battery')
              });
            }
          } catch {
            resolve(null);
          }
        }
      );
    });
  }

  if (process.platform === 'darwin') {
    return new Promise((resolve) => {
      execFile('pmset', ['-g', 'batt'], { timeout: 3000 }, (err, stdout) => {
        if (err || !stdout) return resolve(null);
        try {
          const match = stdout.match(/(\d+)%;\s*([^;]+);/i);
          if (match) {
            const percent = parseInt(match[1], 10);
            const statusWord = (match[2] || '').trim().toLowerCase();
            const charging = statusWord.includes('charging') || statusWord.includes('finishing charge');
            resolve({
              percent,
              charging,
              statusText: statusWord ? (statusWord.charAt(0).toUpperCase() + statusWord.slice(1)) : (charging ? 'Charging' : 'On Battery')
            });
          } else {
            resolve(null);
          }
        } catch {
          resolve(null);
        }
      });
    });
  }

  // Linux: check /sys/class/power_supply
  try {
    const batPath = '/sys/class/power_supply/BAT0';
    if (fs.existsSync(batPath)) {
      const cap = parseInt(fs.readFileSync(path.join(batPath, 'capacity'), 'utf8').trim(), 10);
      const stat = fs.readFileSync(path.join(batPath, 'status'), 'utf8').trim();
      const charging = stat.toLowerCase().includes('charging');
      return Promise.resolve({
        percent: cap,
        charging,
        statusText: stat
      });
    }
  } catch {}

  return Promise.resolve(null);
}

/**
 * Resolves the true desktop directory (accounting for OneDrive redirection on Windows).
 */
function getDesktopPath() {
  const home = os.homedir();
  if (process.platform === 'win32') {
    const oneDriveDesktop = path.join(home, 'OneDrive', 'Desktop');
    if (fs.existsSync(oneDriveDesktop)) return oneDriveDesktop;
  }
  const stdDesktop = path.join(home, 'Desktop');
  if (fs.existsSync(stdDesktop)) return stdDesktop;
  return stdDesktop;
}

/**
 * Counts and lists all folders present directly on the user's Desktop.
 */
function desktopFoldersSnapshot() {
  const desktopPath = getDesktopPath();
  if (!fs.existsSync(desktopPath)) {
    return {
      ok: false,
      error: `Desktop path not found at "${desktopPath}"`,
      path: desktopPath,
      count: 0,
      folders: []
    };
  }

  try {
    const entries = fs.readdirSync(desktopPath, { withFileTypes: true });
    const folders = entries
      .filter((e) => e.isDirectory() && !e.name.startsWith('.') && !e.name.startsWith('$'))
      .map((e) => e.name)
      .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }));

    return {
      ok: true,
      path: desktopPath,
      count: folders.length,
      folders
    };
  } catch (err) {
    return {
      ok: false,
      error: err.message || 'Failed to read desktop folders',
      path: desktopPath,
      count: 0,
      folders: []
    };
  }
}

/**
 * Discovers and audits all screen recordings across standard Windows/Mac capture folders.
 */
function screenRecordingsSnapshot() {
  const home = os.homedir();
  const videoExts = new Set(['.mp4', '.mov', '.mkv', '.webm', '.avi', '.wmv']);

  const candidateDirs = [
    path.join(home, 'Videos', 'Screen Recordings'),
    path.join(home, 'Videos', 'ScreenRecordings'),
    path.join(home, 'Videos', 'Captures'),
    path.join(home, 'Videos'),
    path.join(home, 'OneDrive', 'Videos', 'Screen Recordings'),
    path.join(home, 'OneDrive', 'Videos', 'ScreenRecordings'),
    path.join(home, 'OneDrive', 'Videos', 'Captures'),
    path.join(home, 'OneDrive', 'Videos'),
    path.join(home, 'Pictures', 'Screenshots'),
    path.join(home, 'OneDrive', 'Pictures', 'Screenshots'),
    path.join(home, 'Movies'),
    path.join(home, 'Desktop'),
    path.join(home, 'OneDrive', 'Desktop')
  ];

  const found = [];
  const seenPaths = new Set();
  const locationCounts = new Map();

  for (const dir of candidateDirs) {
    if (!fs.existsSync(dir)) continue;
    try {
      const files = fs.readdirSync(dir, { withFileTypes: true });
      for (const f of files) {
        if (!f.isFile()) continue;
        const ext = path.extname(f.name).toLowerCase();
        if (!videoExts.has(ext)) continue;

        // If scanning Desktop, only count videos that match recording patterns or if reasonable
        const isDesktop = dir.toLowerCase().includes('desktop');
        if (isDesktop && !/screen|recording|clip|capture|record|obs|stream/i.test(f.name)) {
          continue;
        }

        const fullPath = path.join(dir, f.name);
        if (seenPaths.has(fullPath.toLowerCase())) continue;
        seenPaths.add(fullPath.toLowerCase());

        try {
          const stat = fs.statSync(fullPath);
          const dirRelative = path.relative(home, dir) || path.basename(dir);
          found.push({
            name: f.name,
            path: fullPath,
            folder: dirRelative,
            sizeBytes: stat.size,
            mtime: stat.mtime
          });

          locationCounts.set(dirRelative, (locationCounts.get(dirRelative) || 0) + 1);
        } catch {}
      }
    } catch {}
  }

  // Sort by modification date (newest recordings first)
  found.sort((a, b) => b.mtime - a.mtime);

  const totalBytes = found.reduce((acc, f) => acc + f.sizeBytes, 0);

  const locations = Array.from(locationCounts.entries()).map(([dir, count]) => ({
    dir,
    count
  }));

  const recent = found.slice(0, 10).map((f) => ({
    name: f.name,
    folder: f.folder,
    sizeMb: mb(f.sizeBytes),
    date: f.mtime ? new Date(f.mtime).toLocaleDateString() : ''
  }));

  return {
    ok: true,
    count: found.length,
    totalBytes,
    totalMb: mb(totalBytes),
    totalGb: Math.round((totalBytes / (1024 ** 3)) * 100) / 100,
    locations,
    recent
  };
}

/**
 * Top RAM-consuming processes grouped by application name.
 */
function topProcessesSnapshot(limit = 10) {
  const ram = ramSnapshot();

  if (process.platform === 'win32') {
    return new Promise((resolve) => {
      execFile(
        'powershell.exe',
        [
          '-NoProfile',
          '-NonInteractive',
          '-Command',
          `Get-Process | Where-Object { $_.WorkingSet64 -gt 20MB } | Group-Object -Property ProcessName | ForEach-Object {
            $bytes = ($_.Group | Measure-Object -Property WorkingSet64 -Sum).Sum
            [PSCustomObject]@{
              name = $_.Name
              instances = $_.Count
              bytes = $bytes
              mb = [math]::Round($bytes / 1MB, 1)
            }
          } | Sort-Object bytes -Descending | Select-Object -First ${limit} | ConvertTo-Json -Compress`
        ],
        { timeout: 7000, windowsHide: true, maxBuffer: 1024 * 512 },
        (err, stdout) => {
          if (err || !stdout) {
            return resolve({
              ok: true,
              ram,
              processes: []
            });
          }
          try {
            const raw = JSON.parse(String(stdout || '[]').trim() || '[]');
            const list = Array.isArray(raw) ? raw : (raw?.name ? [raw] : []);
            const friendlyMap = {
              'msedge': 'Microsoft Edge',
              'chrome': 'Google Chrome',
              'Antigravity IDE': 'Antigravity IDE',
              'code': 'VS Code',
              'claude': 'Claude Desktop',
              'electron': 'FloatGPT (Electron)',
              'node': 'Node.js Engine',
              'MsMpEng': 'Windows Defender',
              'explorer': 'Windows Explorer',
              'spotify': 'Spotify',
              'discord': 'Discord',
              'slack': 'Slack',
              'teams': 'Microsoft Teams',
              'language_server_windows_x64': 'TypeScript/TSX Language Server'
            };

            const processes = list.map((p) => ({
              name: p.name,
              displayName: friendlyMap[p.name] || p.name,
              instances: Number(p.instances) || 1,
              bytes: Number(p.bytes) || 0,
              mb: Number(p.mb) || mb(p.bytes)
            }));

            resolve({
              ok: true,
              ram,
              processes
            });
          } catch {
            resolve({ ok: true, ram, processes: [] });
          }
        }
      );
    });
  }

  // macOS / POSIX fallback using ps
  return new Promise((resolve) => {
    execFile(
      'ps',
      ['-eo', 'rss,comm'],
      { timeout: 4000 },
      (err, stdout) => {
        if (err || !stdout) {
          return resolve({ ok: true, ram, processes: [] });
        }
        try {
          const lines = stdout.trim().split('\n').slice(1);
          const map = new Map();
          for (const line of lines) {
            const parts = line.trim().split(/\s+/);
            if (parts.length >= 2) {
              const rssKb = parseInt(parts[0], 10) || 0;
              const cmdPath = parts.slice(1).join(' ');
              const name = path.basename(cmdPath);
              const current = map.get(name) || { name, instances: 0, bytes: 0 };
              current.instances += 1;
              current.bytes += rssKb * 1024;
              map.set(name, current);
            }
          }
          const sorted = Array.from(map.values())
            .sort((a, b) => b.bytes - a.bytes)
            .slice(0, limit)
            .map((p) => ({
              name: p.name,
              displayName: p.name,
              instances: p.instances,
              bytes: p.bytes,
              mb: mb(p.bytes)
            }));

          resolve({ ok: true, ram, processes: sorted });
        } catch {
          resolve({ ok: true, ram, processes: [] });
        }
      }
    );
  });
}

/**
 * Launches OS Task Manager / Activity Monitor.
 */
function openTaskManager() {
  try {
    if (process.platform === 'win32') {
      const child = spawn('taskmgr.exe', [], { detached: true, stdio: 'ignore' });
      child.unref();
      return { ok: true, app: 'Task Manager' };
    }
    if (process.platform === 'darwin') {
      const child = spawn('open', ['-a', 'Activity Monitor'], { detached: true, stdio: 'ignore' });
      child.unref();
      return { ok: true, app: 'Activity Monitor' };
    }
    const child = spawn('gnome-system-monitor', [], { detached: true, stdio: 'ignore' });
    child.unref();
    return { ok: true, app: 'System Monitor' };
  } catch (err) {
    return { ok: false, error: err.message };
  }
}

/**
 * Universal OS Diagnostics Snapshot Dispatcher
 */
async function snapshot(kind) {
  try {
    const k = String(kind || 'system').toLowerCase();

    if (k === 'desktop_folders' || k === 'folders_on_desktop') {
      const folders = desktopFoldersSnapshot();
      return {
        ok: folders.ok !== false,
        error: folders.error,
        desktopFolders: {
          path: folders.path,
          count: folders.count,
          folders: folders.folders || []
        }
      };
    }

    if (k === 'screen_recordings' || k === 'recordings') {
      const recordings = screenRecordingsSnapshot();
      return {
        ok: recordings.ok !== false,
        error: recordings.error,
        screenRecordings: recordings
      };
    }

    if (k === 'top_processes' || k === 'ram_hogs' || k === 'processes_ram') {
      return await topProcessesSnapshot(10);
    }

    if (k === 'open_taskmgr_and_ram' || k === 'open_task_manager') {
      const opened = openTaskManager();
      const top = await topProcessesSnapshot(10);
      return {
        ...top,
        taskManagerOpened: opened.ok,
        openedAppName: opened.app
      };
    }

    const ram = ramSnapshot();
    const out = {
      ok: true,
      hostname: os.hostname(),
      platform: process.platform,
      uptimeSec: Math.round(os.uptime()),
      ram
    };

    if (k === 'ram') return out;

    if (k === 'cpu') {
      out.cpu = await cpuSnapshot();
      return out;
    }

    if (k === 'battery') {
      out.battery = await batterySnapshot();
      return out;
    }

    // Full system snapshot
    out.cpu = await cpuSnapshot();
    out.battery = await batterySnapshot();
    out.desktopFolders = desktopFoldersSnapshot();
    return out;
  } catch (err) {
    return { ok: false, error: (err && err.message) || 'Diagnostics failed' };
  }
}

function looksTruncatedScript(script) {
  const s = String(script || '').trim();
  if (!s) return true;
  const dq = (s.match(/"/g) || []).length;
  const sq = (s.match(/'/g) || []).length;
  if (dq % 2 === 1 || sq % 2 === 1) return true;
  if (/[({,=]\s*$/.test(s)) return true;
  if (/\bGet-WmiObject\s+Win[0-9]*$/i.test(s)) return true;
  if (/\bGet-CimInstance\s+Win[0-9]*$/i.test(s)) return true;
  return false;
}

function isHardwareQueryScript(script) {
  const s = String(script || '');
  return /\b(Win32_OperatingSystem|Win32_ComputerSystem|Win32_Processor|Win32_Battery|FreePhysicalMemory|TotalVisibleMemorySize|GlobalMemoryStatus|virtual_memory|os\.totalmem)\b/i.test(s)
    || (/\b(RAM|memory load|Get-WmiObject\s+Win32)\b/i.test(s) && /\b(FreePhysical|TotalVisible|WorkingSet|PercentProcessor)\b/i.test(s));
}

module.exports = {
  snapshot,
  ramSnapshot,
  cpuSnapshot,
  batterySnapshot,
  desktopFoldersSnapshot,
  screenRecordingsSnapshot,
  topProcessesSnapshot,
  openTaskManager,
  looksTruncatedScript,
  isHardwareQueryScript
};
