/**
 * FloatGPT — Study System & Research Pack Generator
 * 
 * Generates structured Flashcards, Definitions, Multiple-Choice Questions (MCQs),
 * and Revision Checklists from document or note inputs.
 */

export interface Flashcard {
  id: string;
  front: string;
  back: string;
  topic?: string;
}

export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export interface StudyPack {
  packId: string;
  title: string;
  summary: string;
  keyConcepts: { concept: string; definition: string }[];
  flashcards: Flashcard[];
  quiz: QuizQuestion[];
  revisionChecklist: string[];
  createdAt: number;
}

export class StudySystem {
  /**
   * Generates a structured Study Pack from text/markdown content.
   */
  static generateStudyPack(title: string, content: string): StudyPack {
    const lines = content.split('\n').map(l => l.trim()).filter(Boolean);
    const keyConcepts: { concept: string; definition: string }[] = [];
    const flashcards: Flashcard[] = [];
    const revisionChecklist: string[] = [];

    lines.forEach((line, idx) => {
      // Concept: Definition pattern
      if (line.includes(':') && line.length < 200 && !line.startsWith('http')) {
        const [concept, ...defParts] = line.split(':');
        const cleanConcept = concept.replace(/^[-*•#\d.]+\s*/, '').trim();
        const cleanDef = defParts.join(':').trim();
        if (cleanConcept.length > 2 && cleanDef.length > 5) {
          keyConcepts.push({ concept: cleanConcept, definition: cleanDef });
          flashcards.push({
            id: `fc_${idx}`,
            front: cleanConcept,
            back: cleanDef
          });
          revisionChecklist.push(`Review concept: ${cleanConcept}`);
        }
      } else if (line.startsWith('-') || line.startsWith('*') || line.startsWith('•')) {
        const point = line.replace(/^[-*•]+\s*/, '').trim();
        if (point.length > 10) {
          revisionChecklist.push(point);
        }
      }
    });

    const sampleQuiz: QuizQuestion[] = keyConcepts.slice(0, 3).map((kc, i) => ({
      id: `q_${i}`,
      question: `What is the definition of "${kc.concept}"?`,
      options: [
        kc.definition,
        'An unrelated background process',
        'None of the above'
      ],
      correctIndex: 0,
      explanation: `${kc.concept} refers to: ${kc.definition}`
    }));

    return {
      packId: Math.random().toString(36).substring(2, 9),
      title: title || 'FloatGPT Study Pack',
      summary: lines.slice(0, 2).join(' ') || 'Study Pack generated by FloatGPT.',
      keyConcepts: keyConcepts.slice(0, 10),
      flashcards: flashcards.slice(0, 12),
      quiz: sampleQuiz,
      revisionChecklist: revisionChecklist.slice(0, 8),
      createdAt: Date.now()
    };
  }
}
